name: Go build

on: [push, pull_request]

jobs:
  build:
    name: Build Go
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.13'
    - name: Check out code
      uses: actions/checkout@v2
    - name: Check go fmt has been run
      run: |
        echo 'Check if go fmt has been run'
        make go_fmt
        [[ "$(git diff --name-only | wc -l)" -eq "0" ]]
    - name: Build
      run: make
